about_widget_content = "Study. Productivity. Growth. Learn to become the best you can be with daily articles on revision, relaxation, mindfulness, and more!"
address = "Manchester, UK"
author = "Erin McG"
contact_form_action = "https://us20.list-manage.com/contact-form?u=92c148d9ebf9778789f747555&form_id=ee6912d833da8aee66b51c5a914ea9c0"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
custom_script = ""
description = "Study. Productivity. Growth."
email = "studicacti@gmail.com"
favicon = "images/cacfav.png"
featured_post_title = "Featured Post"
footer_content = "Study. Productivity. Growth. "
image = "images/logo.png"
logo = "images/cacti.png"
logo_text = "Boilerplate"
logo_width = "150x"
mainSections = ["blog"]
mobile = ""
navbar_fixed = false
recent_post_title = "Recent Posts"
search = true
[advertisement]
image = "images/promotion.png"
link = "https://gethugothemes.com/"
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Learn More"
button_link = "about/"
content = "Learn to study effectively. Learn to make the most of your skills. Learn to build relationships. Learn to live with studi **cacti**"
enable = true
image = "images/cacfav.png"
title_large = "Studi **Cacti**"
title_small = "Study. Productivity. Growth."
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = true
expire_days = 2
[preloader]
enable = false
preloader = ""
[subscription]
enable = true
mailchimp_form_action = "http://eepurl.com/hRgrJn"
mailchimp_form_name = "http://eepurl.com/hRgrJn"
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
[[social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "#"
title = "instagram"
[[social]]
icon = "fab fa-github"
link = "#"
title = "github"
[[social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
